USE DATABASE ANALYTICS_DB;
CREATE OR REPLACE SCHEMA EDW;
CREATE OR REPLACE TABLE DIM_CLIENT
(
    ClientID INT,
    DateKey DATE NOT NULL,
    ProductKey INT NOT NULL,
    CustomerKey INT NOT NULL,
    StoreKey INT NOT NULL,
    SalesAmount DECIMAL(10, 2) NOT NULL,
    Quantity INT NOT NULL
);
