CREATE OR REPLACE DATABASE ANALYTICS_DB;
CREATE OR REPLACE SCHEMA STAGE;
CREATE OR REPLACE TABLE STG_CLIENT
(
    ClientID INT,
    DateKey DATE NOT NULL,
    ProductKey INT NOT NULL,
    CustomerKey INT NOT NULL,
    StoreKey INT NOT NULL,
    SalesAmount DECIMAL(10, 2) NOT NULL,
    Quantity INT NOT NULL
);
